### ISSUE TITLE
pals: submitting tags with uppercase characters gives 400

### ISSUE THREAD

**Issue by Fang-** [Fang-/suite#4]
Should probably just automatically lowercase for you, and maybe even remove any other "illicit" characters.

Alternatively we could consider making tags/lists not strictly `@ta`, but this complicated the scry interface and generally has poor aesthetics.

**Comment by afknapping** [comment]
I came here because of this. it took me several months to find out why some tags are just not saved. this is *really* frustrating

so [for the love of god and all that is holy](https://www.youtube.com/watch?v=UcwfEMdV-aM&t=72s), please give UI feedback when a tag cannot be saved and tell me what i need to do to make it work ✌️


PS:

if you want to talk about how else this (or any other app) could be improved, i just set up a calendly for usability sparring: https://calendly.com/tanpen-ridlyt/usability-sparring

**Comment by afknapping** [comment]
in case that came off as rude – apologies, wasn't meant like that at all

**Comment by Fang-** [comment]
It was a little bit rude, but I get the message! New pals update is in progress, I'll make sure to include a fix for this.
