### ISSUE TITLE
fafa: needs a secret backup solution

### ISSUE THREAD

**Issue by m-rio** [Fang-/suite#8]
where are the secrets stored? so we could export them/backup.

**Comment by Fang-** [comment]
They're in `/app/fafa`'s state as raw atoms. I had considered blanking them out in the dbug state scry, but forgot about that. So right now, you can get them out through `:fafa +dbug` or some variation thereon, but I'll probably make that impossible going forward. (Local access to OTPs is one thing, but scrying out the secrets probably shouldn't be so trivial.)

I'd be down to implement ex/import functionality but afaia there's no standard for that in the (T)OTP context. Do you just want to ex/import to/from instances of this app, or also other authenticators?

**Comment by m-rio** [comment]
`:fafa +dbug` does work ;)

My motivation right now is to know I can keep these backed up in case my urbit somehow dies and I can still access various accounts and (optionally) create new 2FA secrets. I guess standard backup of my whole ship will serve for now as long as I have the ability to run fafa even if ship became inoperable. or at least we know how to convert the raw atoms into the actual secrets - which, as a hoon ignorant, I don´t ;P

Importing from external tools would be great too! right now I'm manually copying from a dumped json of my existing authenticator tool.

**Comment by Fang-** [comment]
> how to convert the raw atoms into the actual secrets

The atoms are just the secret values. They're commonly encoded/displayed in base32. We presently only need/implement decoding, but there exist outside-of-urbit tools for encoding.

> dumped json of my existing authenticator tool.

What's the name of the authenticator tool? I might want to investigate.

Scrying is quite robust since (theoretically) as long as you have a snapshot, you can run a scry against it. This doesn't apply to the time-based codes though, because you can only scry into agents at the current timestamp, which (if I understand correctly) is static for snapshots. So you'd want to scry out the full secrets, but then the security consideration I mentioned comes into play again.

I think what I might want to do is have it write to a backup file in `.urb/put`, and then provide some functionality for importing that back in. That doesn't seem too bad.
